int _putchar(char);
int print_alphabet();
int print_alphabet_x10();
int _islower(int);
int _isalpha(int);
int print_sign(int);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int);
void print_times_table(int);
void multiples_3_or_5(void);
